import express from "express";
import userRoutes from "../modules/user/user.routes";
import userPasswordRoutes from "../modules/userPassword/userPassword.routes";
import sectionRoutes from "../modules/section/section.routes";
import sectionRowRoutes from "../modules/sectionRow/sectionRow.routes";
import rowRoutes from "../modules/row/row.routes";
import rowsColumnRoutes from "../modules/rowsColumn/rowsColumn.routes";
import columnRoutes from "../modules/column/column.routes";
import columnInputRoutes from "../modules/columnInput/columnInput.routes";
import inputRoutes from "../modules/input/input.routes";
import inputTypeRoutes from "../modules/inputType/inputType.routes";
import inputValueRoutes from "../modules/inputValue/inputValue.routes";
import inputEntityRoutes from "../modules/inputEntity/inputEntity.routes";
import inputEntityValueRoutes from "../modules/inputEntityValue/inputEntityValue.routes";
import dropdownEntityValueRoutes from "../modules/dropdownEntityValue/dropdownEntityValue.routes";
import dropdownOptionRoutes from "../modules/dropdownOption/dropdownOption.routes";
import quantityRoutes from "../modules/quantity/quantity.routes";
import quantityOptionRoutes from "../modules/quantityOption/quantityOption.routes";
import formatRoutes from "../modules/format/format.routes";
import templateRoutes from "../modules/template/template.routes";
import templateSectionRoutes from "../modules/templateSection/templateSection.routes";
import templateSectionRowRoutes from "../modules/templateSectionRow/templateSectionRow.routes";
import templateRowRoutes from "../modules/templateRow/templateRow.routes";
import templateRowsColumnRoutes from "../modules/templateRowsColumn/templateRowsColumn.routes";
import templateColumnRoutes from "../modules/templateColumn/templateColumn.routes";
import templateColumnInputRoutes from "../modules/templateColumnInput/templateColumnInput.routes";
import templateInputRoutes from "../modules/templateInput/templateInput.routes";
import renderedOutputRoutes from "../modules/renderedOutput/renderedOutput.routes";
import AuthRoutes from "../modules/auth/auth.routes";
const router = express.Router();

router.use("/users", userRoutes);
router.use("/user-passwords", userPasswordRoutes);
router.use("/sections", sectionRoutes);
router.use("/section-rows", sectionRowRoutes);
router.use("/rows", rowRoutes);
router.use("/rows-columns", rowsColumnRoutes);
router.use("/columns", columnRoutes);
router.use("/column-inputs", columnInputRoutes);
router.use("/inputs", inputRoutes);
router.use("/input-types", inputTypeRoutes);
router.use("/input-values", inputValueRoutes);
router.use("/input-entities", inputEntityRoutes);
router.use("/input-entity-values", inputEntityValueRoutes);
router.use("/dropdown-entity-values", dropdownEntityValueRoutes);
router.use("/dropdown-options", dropdownOptionRoutes);
router.use("/quantities", quantityRoutes);
router.use("/quantity-options", quantityOptionRoutes);
router.use("/formats", formatRoutes);
router.use("/templates", templateRoutes);
router.use("/template-sections", templateSectionRoutes);
router.use("/template-section-rows", templateSectionRowRoutes);
router.use("/template-rows", templateRowRoutes);
router.use("/template-rows-columns", templateRowsColumnRoutes);
router.use("/template-columns", templateColumnRoutes);
router.use("/template-column-inputs", templateColumnInputRoutes);
router.use("/template-inputs", templateInputRoutes);
router.use("/rendered-outputs", renderedOutputRoutes);
router.use("/auth",AuthRoutes)
export default router;
